version: "3.9"

services:
  app:
    build: .
    container_name: portfolio-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - portfolio-net
    environment:
      NODE_ENV: production
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      node scripts/seedProjetos.js &&
      node app.js
      "
    db:
      image: postgres:15-alpine
      container_name: portfolio-db
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - portfolio-net
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
        interval: 5s
        timeout: 5s
        retries: 10

volumes:
  pgdata:

networks:
  portfolio-net:
